### ISSUE TITLE
Mismatched instr_embed_size.

### ISSUE THREAD

**Issue by turn0the0table** [cshizhe/robot_sugar#3]
During the reproduction of the paper, I noticed that the instr_embed_size in the training_config of the trained model you provided is set to 1280, whereas PolarNet uses CLIP to generate an instr_embed_size of 512. It seems that the results cannot be directly evaluated. Should further data processing be performed?

**Comment by cshizhe** [comment]
Hi, SUGAR and PolarNet are two different models. You cannot run PolarNet with the codes in SUGAR.

**Comment by turn0the0table** [comment]
In the "Language-guided robotic manipulation" section, the trained model of SUGAR you provided expects an input length of 1280 for instr_embed_size, whereas the instr_embed_size of the dataset mentioned in dataset.md is 512.The dataset and the model seems do not match.

**Comment by cshizhe** [comment]
The dataset.md does not mention the instr_embed_size. Could you show me where you find it?
In SUGAR, we use a larger clip model as shown [here](https://github.com/cshizhe/robot_sugar/blob/main/robo3d/models/clip_encoder.py#L102) to extract the instruction embeddings instead of the [clip base mode](https://github.com/cshizhe/robot_sugar/blob/main/robo3d/models/clip_encoder.py#L43) in PolarNet.

**Comment by turn0the0table** [comment]
So  [here](https://github.com/cshizhe/robot_sugar/blob/8299fa80749c4233ba954ac54a0a7802da5cad7d/DATASET.md?plain=1#L25) we can't use the training dataset download or generate from [PolarNet](https://github.com/vlc-robot/polarnet/?tab=readme-ov-file) for the 10 robotic manipulation tasks? The instr_embed_size length of the dataset I downloaded from PolarNet is 512.
